version: '3.7'
services:
  web:
    container_name:  "burb-web"
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - api
  api:
    container_name:  "burb-api"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./api/uploads:/usr/src/app/uploads"
    networks:
      - default
    depends_on:
      - db
  db:
    container_name: "burb-db"
    image: postgres:latest
    #w volumes:
      #w - "./db/db-data/:/var/lib/postgresql/data/"
    # ports:
      # - 5432:5432
    networks:
      - default
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)"

#define network
networks:
  default:
    driver: bridge