version: '3.7'
services:
  web:
    container_name:  "burb-web"
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - api
  api:
    container_name:  "burb-api"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./ftp/data:/usr/src/app/uploads"
    networks:
      - default
  ftp:
    container_name:  "burb-ftp"
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./ftp/data:/home/username/"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
  python:
    container_name:  "burb-python"
    build:
      context: ./burb
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    volumes:
      - "./ftp/data:/folder-in-container"
    networks:
      - default
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# or ssl/tls with Let's Encrypt (cert and key as two files)
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "134.122.86.78"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
  redis:
    container_name: "burb-redis"
    image: redis:latest
    volumes:
      - "./db/redis/data:/data"
    ports:
      - '6379:6379'
    networks:
      - default

#define network
networks:
  default:
    driver: bridge
